[versions]

# Minecraft
minecraft = "1.21.1"
neoforge = "21.1.72"
parchment = "2024.07.28"

# Dependencies
rlib = "3.0.11"
olympus = "1.0.8"

# Plugins
moddev = "0.1.126"

[libraries]

rlib = { module = "com.teamresourceful.resourcefullib:resourcefullib-neoforge-1.21", version.ref = "rlib" }
olympus = { module = "earth.terrarium.olympus:olympus-neoforge-1.21", version.ref = "olympus" }

[plugins]

moddev = { id = "net.neoforged.moddev", version.ref = "moddev" }